FROM node:16

ENV PORT 3000

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json /usr/src/app/
COPY yarn.lock /usr/src/app/

RUN yarn install

COPY . /usr/src/app

VOLUME "usr/src/app/out"

RUN yarn build

CMD [ "yarn", "start" ]