name: Build next.js

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: go to project directory
        run: cd fd-web

      - name: Building docker image
        run: docker build -t fd-web .

      - name: Run tests
        run: docker run --name fd-web -p 3001:3000 fd-web yarn test
